export { globalsProxy } from "./globals.js";
export { createModuleShimCodeCjs, createModuleShimCodeEsm } from "./module.js";
export { createPathShimCodeCjs, createPathShimCodeEsm } from "./path.js";
export { createVmShimCodeCjs, createVmShimCodeEsm } from "./vm.js";
export { createHttpShimCodeCjs, createHttpShimCodeEsm } from "./http.js";
export { createDnsShimCodeCjs, createDnsShimCodeEsm } from "./dns.js";
export { createDgramShimCodeCjs, createDgramShimCodeEsm } from "./dgram.js";
export { createFsShimCodeCjs, createFsShimCodeEsm } from "./fs.js";
export { createChildProcessShimCodeCjs, createChildProcessShimCodeEsm } from "./child_process.js";
export { createCryptoShimCodeCjs, createCryptoShimCodeEsm } from "./crypto.js";
